/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafe.management.system;

import javax.swing.JOptionPane;

/**
 *
 * @author girip
 */
public class Home extends javax.swing.JFrame {
    public String email;

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    public Home(String userEmail) {
        initComponents();
        email=userEmail;
        if(!email.equals("admin@gmail.com")){
            BtnManageCategory.setVisible(false);
            BtnNewProduct.setVisible(false);
            BtnViewEditDeleteProduct.setVisible(false);
            BtnVerifyUsers.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnLogout = new javax.swing.JButton();
        BtnPlaceOrder = new javax.swing.JButton();
        BtnViewBillOrderPlacedDetails = new javax.swing.JButton();
        BtnChangePassword = new javax.swing.JButton();
        BtnChangeSecurityQuestion = new javax.swing.JButton();
        BtnExit = new javax.swing.JButton();
        BtnManageCategory = new javax.swing.JButton();
        BtnNewProduct = new javax.swing.JButton();
        BtnViewEditDeleteProduct = new javax.swing.JButton();
        BtnVerifyUsers = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnLogout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        BtnLogout.setText("Logout");
        BtnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(BtnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        BtnPlaceOrder.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnPlaceOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/place order.png"))); // NOI18N
        BtnPlaceOrder.setText("Place Order");
        getContentPane().add(BtnPlaceOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        BtnViewBillOrderPlacedDetails.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnViewBillOrderPlacedDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/View Bills & Order Placed Details.png"))); // NOI18N
        BtnViewBillOrderPlacedDetails.setText("View Bill & Order Placed Details");
        getContentPane().add(BtnViewBillOrderPlacedDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, -1, -1));

        BtnChangePassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnChangePassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/change Password.png"))); // NOI18N
        BtnChangePassword.setText("Change Password");
        BtnChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnChangePasswordActionPerformed(evt);
            }
        });
        getContentPane().add(BtnChangePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, -1, -1));

        BtnChangeSecurityQuestion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnChangeSecurityQuestion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/change Security Question.png"))); // NOI18N
        BtnChangeSecurityQuestion.setText("Change Security Question");
        BtnChangeSecurityQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnChangeSecurityQuestionActionPerformed(evt);
            }
        });
        getContentPane().add(BtnChangeSecurityQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 20, -1, -1));

        BtnExit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        BtnExit.setText("Exit");
        BtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExitActionPerformed(evt);
            }
        });
        getContentPane().add(BtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 20, -1, -1));

        BtnManageCategory.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnManageCategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/category.png"))); // NOI18N
        BtnManageCategory.setText("Manage Category");
        BtnManageCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnManageCategoryActionPerformed(evt);
            }
        });
        getContentPane().add(BtnManageCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 710, -1, -1));

        BtnNewProduct.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnNewProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new product.png"))); // NOI18N
        BtnNewProduct.setText("New Product");
        BtnNewProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNewProductActionPerformed(evt);
            }
        });
        getContentPane().add(BtnNewProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 710, -1, -1));

        BtnViewEditDeleteProduct.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnViewEditDeleteProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/view edit delete product.png"))); // NOI18N
        BtnViewEditDeleteProduct.setText("View ,Edit & Delete Product");
        getContentPane().add(BtnViewEditDeleteProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 710, -1, -1));

        BtnVerifyUsers.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnVerifyUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/verify users.png"))); // NOI18N
        BtnVerifyUsers.setText("Verify Users");
        BtnVerifyUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVerifyUsersActionPerformed(evt);
            }
        });
        getContentPane().add(BtnVerifyUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 710, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home-background-image.png"))); // NOI18N
        jLabel1.setText("homebackgound");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExitActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do You Really Want To Close Application","Select",JOptionPane.YES_NO_OPTION);
        if(a==0){
            System.exit(0);
        }
    }//GEN-LAST:event_BtnExitActionPerformed

    private void BtnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLogoutActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do You Really Want To LOgout","Select",JOptionPane.YES_NO_OPTION);
        if(a==0){
            setVisible(false);
            new login().setVisible(true);
        }
    }//GEN-LAST:event_BtnLogoutActionPerformed

    private void BtnManageCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnManageCategoryActionPerformed
        // TODO add your handling code here:
        new ManageCategory().setVisible(true);
    }//GEN-LAST:event_BtnManageCategoryActionPerformed

    private void BtnNewProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNewProductActionPerformed
        // TODO add your handling code here:
        new Addnewproduct().setVisible(true);
    }//GEN-LAST:event_BtnNewProductActionPerformed

    private void BtnVerifyUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVerifyUsersActionPerformed
        // TODO add your handling code here:
        new VerifyUsers().setVisible(true);
    }//GEN-LAST:event_BtnVerifyUsersActionPerformed

    private void BtnChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnChangePasswordActionPerformed
        // TODO add your handling code here:
       new ChangePassword(email).setVisible(true); 
    }//GEN-LAST:event_BtnChangePasswordActionPerformed

    private void BtnChangeSecurityQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnChangeSecurityQuestionActionPerformed
        // TODO add your handling code here:
        new ChangeSecurityQuestion(email).setVisible(true);
    }//GEN-LAST:event_BtnChangeSecurityQuestionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnChangePassword;
    private javax.swing.JButton BtnChangeSecurityQuestion;
    private javax.swing.JButton BtnExit;
    private javax.swing.JButton BtnLogout;
    private javax.swing.JButton BtnManageCategory;
    private javax.swing.JButton BtnNewProduct;
    private javax.swing.JButton BtnPlaceOrder;
    private javax.swing.JButton BtnVerifyUsers;
    private javax.swing.JButton BtnViewBillOrderPlacedDetails;
    private javax.swing.JButton BtnViewEditDeleteProduct;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
